### ISSUE TITLE
Send ban reason to thread creator if live update thread is banned

### ISSUE THREAD

**Issue by rctgamer3** [reddit/reddit-plugin-liveupdate#164]
Backstory: Our newest Twitch Plays Pokémon [live thread](https://www.reddit.com/live/zmxw6yogfa8q) was falsely hit because of a spamwave.
For non-logged-in users, it displays that the thread was banned, but all approved submitters do not, and submitters with full permissions (aka the updater mods) are left in the dark.

Wouldn't it be an improvement to send a reddit message to the creator of the updater (should likely be me in our specific case) with an update why/for what reason it was banned?

(If a thread is banned, would the thread creator of the banned thread be allowed to create a new thread or would that be considered ban evasion if created by the same user?)

**Comment by spladug** [comment]
So far we've only really banned for spam. In that case, we really really don't want to tell the user that it's banned (which is why the banned thread still appears normally to anyone with contributor access) in the hopes that they keep on keepin' on without making a new thread. This is just a standard anti-spam tactic across the site.

I know this sucks for regular users who get caught in the crossfire (sorry!) but hopefully as we evolve the anti-spam measures here it should be less likely that anyone non-spammy will be affected.
